Make the download for each sub run in parallel
In local testing this reduced the execution time from ~20s to ~10s.
There is also some additional logging added to help give more feedback
to the user about what is happening.

diff --git a/dank b/dank
--- a/dank
+++ b/dank
@@ -2,10 +2,10 @@
 
 set -euo pipefail
 
-VERSION="1.2.0"
+VERSION="1.3.0"
 FLAG_SERVE="false"
 
-dir=$(mktemp /tmp/memes-XXXXX)
+dir=$(mktemp /tmp/memes-XXXXX); export dir
 
 subs=(
   "memes"
@@ -16,23 +16,27 @@ subs=(
 )
 
 # Logging utilities
-function log::_timestamp() { date +'%Y-%m-%dT%H:%M:%S%z'; }
-function log::info() { echo "$(log::_timestamp) [INFO] $*" >&2; }
-function log::warn() { echo "$(log::_timestamp) [WARN] $*" >&2; }
-function log::error() { echo "$(log::_timestamp) [ERROR] $*" >&2; }
+function log::_timestamp() { date +'%Y-%m-%dT%H:%M:%S%z'; }; export -f log::_timestamp
+function log::info() { echo "$(log::_timestamp) [INFO] $*" >&2; }; export -f log::info
+function log::warn() { echo "$(log::_timestamp) [WARN] $*" >&2; }; export -f log::warn
+function log::error() { echo "$(log::_timestamp) [ERROR] $*" >&2; }; export -f log::error
 
 # Using the reddit api find the top posts and download the images into the directory.
 function download_memes() {
   # Wget sometimes fails to download from some domains blocking scripting, this is fine and we should continue to process
   set +e
+
+  log::info "Downloading memes from /r/${1}"
   
   wget -q -O - "https://reddit.com/r/${1}/top.json?t=day" \
     | jq '.data.children[].data.url' \
     | grep -E '(png|jpg|jpeg)' \
     | xargs -P 32 wget -q -P "${dir}"
 
+  log::info "Finished downloading from /r/${1}"
+
   set -e
-}
+}; export -f download_memes
 
 # Create an html page with all of the images
 function serve_html() {
@@ -84,12 +88,10 @@ function main() {
   parse_args "$@"
 
   log::info "Downloading to ${dir}"
-  log::info "Collecting content from these subs [${subs[*]}]"
+  log::info "Collecting content from these subs [$(printf '%s,' "${subs[@]}")]"
 
-  for i in "${subs[@]}"; do
-    log::info "Downloading memes from /r/${i}"
-    download_memes "${i}"
-  done
+  printf '%s\0' "${subs[@]}" \
+    | xargs -P 32 -n 1 -0 -I '{}' bash -c 'download_memes "{}"'
 
   echo "${dir}"
 
